### ISSUE TITLE
dnsResolve for unknown host

### ISSUE THREAD

**Issue by HynekPetrak** [TooTallNate/node-pac-resolver#12]
Shall dnsResolve return an empty string, rather then to throw an exception?

**Comment by TooTallNate** [comment]
Is that what the web browser does in that scenario?

**Comment by HynekPetrak** [comment]
Yes, I believe so.  I've never seen try/catch in a pac file.
Unknown hosts are quite common if LAN internal DNS is being used.

**Comment by arpitgautam** [comment]
Most modern browsers skips the rule on which exception occurred and carry on with rest of the file.

**Comment by HynekPetrak** [comment]
here we are discussing a node module. How do you want to ignore an exception and continue processing?

**Comment by TooTallNate** [comment]
Patch welcome.
