### ISSUE TITLE
Use regenerator runtime instead of regenerator

### ISSUE THREAD

**Issue by steelbrain** [TooTallNate/node-pac-resolver#13]
The [runtime](https://www.npmjs.com/package/regenerator-runtime) is a LOT more lightweight, this library shouldn't need the other parts anyway. For comparison the runtime has zero deps compared to 7 (which of course have deps themselves)

**Comment by TooTallNate** [comment]
The next major version will probably just drop < Node.js v0.12 support (the first version where Generators were natively supported) in order to reduce file size.
