### ISSUE TITLE
Browserify issue with vm.runInNewContext

### ISSUE THREAD

**Issue by RichardLitt** [TooTallNate/node-pac-resolver#5]
This line in `index.js` is breaking in my build:

``` 
var wg = vm.runInNewContext(regenerator('', { includeRuntime: true }) + ';wrapGenerator');
```

I've no idea why. I seem to be able to just comment it out and everything runs fine, so I'm not sure exactly what it is doing. The issue in the terminal is: `Uncaught TypeError: Cannot set property 'wrapGenerator' of undefined`. Any thoughts?

**Comment by TooTallNate** [comment]
You're really trying to run this _in_ the browser? What's your use-case if you don't mind me asking?

**Comment by RichardLitt** [comment]
I don't mind. It's one of the dependencies in `mailgun-js`. I'm not sure why they're using it; I want to use them with `nodemailer` to send emails from a Chrome extension.

**Comment by RichardLitt** [comment]
[vm-browserify](https://github.com/substack/vm-browserify) ought to make this usable, and I think I'm using that already by just using browserify as it is. But I don't fully understand the scope of the problem. :/

**Comment by TooTallNate** [comment]
I think it's a `vm-browserify` bug actually. See https://github.com/substack/vm-browserify/pull/13.

With that patch applied, I was able to get browserified PacResolver working correctly (well, I wouldn't expect DNS or stuff like that to work, but at least the function compiled and executed with a dummy return value correctly).

**Comment by RichardLitt** [comment]
Looks like you're right. Hopefully this gets pulled in pretty quick. Thanks!

**Comment by TooTallNate** [comment]
Also note that I had to use the "brfs" browserify transform (as a global transform, unfortunately), to make that `fs.readFileSync()` call be inlined: https://github.com/substack/brfs

**Comment by RichardLitt** [comment]
Yep, I had been using that too. Thanks for mentioning it.
